########################################################################
# Copyright (c) 1988-2014 $organization$
#
# This software is provided by the author and contributors ``as is'' 
# and any express or implied warranties, including, but not limited to, 
# the implied warranties of merchantability and fitness for a particular 
# purpose are disclaimed. In no event shall the author or contributors 
# be liable for any direct, indirect, incidental, special, exemplary, 
# or consequential damages (including, but not limited to, procurement 
# of substitute goods or services; loss of use, data, or profits; or 
# business interruption) however caused and on any theory of liability, 
# whether in contract, strict liability, or tort (including negligence 
# or otherwise) arising in any way out of the use of this software, 
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 11/22/2014
#
# Generic Gcc Makefile for texta libtexta Library
########################################################################

#
# user c++ flags
#
libtexta_USRCXXFLAGS += \
${texta_USRCXXFLAGS} \

#
# user defines
#
libtexta_USRDEFINES = \
${texta_USRDEFINES} \

#
# user includes
#
libtexta_USRINCLUDES = \
${texta_USRINCLUDES} \

#
# user libdirs
#
libtexta_USRLIBDIRS = \
${texta_USRLIBDIRS} \

#
# C .c sources
#
libtexta_LIB_C_SOURCES = \

#
# C++ .cxx sources
#
libtexta_LIB_CXX_SOURCES = \

#
# C++ .cpp sources
#
libtexta_LIB_CPP_SOURCES += \
${TEXTA_SRC}/texta/base/base.cpp \

#
# libs
#
libtexta_LIBS = \
-ltexta \
${texta_LIBS} \

