########################################################################
# Copyright (c) 1988-2014 $organization$
#
# This software is provided by the author and contributors ``as is'' 
# and any express or implied warranties, including, but not limited to, 
# the implied warranties of merchantability and fitness for a particular 
# purpose are disclaimed. In no event shall the author or contributors 
# be liable for any direct, indirect, incidental, special, exemplary, 
# or consequential damages (including, but not limited to, procurement 
# of substitute goods or services; loss of use, data, or profits; or 
# business interruption) however caused and on any theory of liability, 
# whether in contract, strict liability, or tort (including negligence 
# or otherwise) arising in any way out of the use of this software, 
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 11/22/2014
#
# Generic Gcc Makefile for texta texta Executable
########################################################################

#
# Executable C++ .cpp sources
#
texta_EXE_CPP_SOURCES += \
${TEXTA_SRC}/texta/t/file_functions.cpp \
${TEXTA_SRC}/texta/t/string_functions.cpp \
${TEXTA_SRC}/texta/t/time_functions.cpp \
${TEXTA_SRC}/texta/t/logical_functions.cpp \
${TEXTA_SRC}/texta/t/conditional_functions.cpp \
${TEXTA_SRC}/texta/t/block_functions.cpp \
${TEXTA_SRC}/texta/t/base_functions.cpp \
${TEXTA_SRC}/texta/t/functions.cpp \

texta_EXE_CPP_SOURCES += \
${TEXTA_SRC}/texta/t/processor.cpp \
${TEXTA_SRC}/texta/t/function_extend.cpp \
${TEXTA_SRC}/texta/t/function_named.cpp \
${TEXTA_SRC}/texta/t/function_tree.cpp \
${TEXTA_SRC}/texta/t/function_branch.cpp \
${TEXTA_SRC}/texta/t/function_list.cpp \
${TEXTA_SRC}/texta/t/function_item.cpp \
${TEXTA_SRC}/texta/t/function.cpp \
${TEXTA_SRC}/texta/t/function_argument.cpp \
${TEXTA_SRC}/texta/t/function_argument_list.cpp \
${TEXTA_SRC}/texta/t/function_argument_item.cpp \
${TEXTA_SRC}/texta/t/function_parameter.cpp \
${TEXTA_SRC}/texta/t/variable.cpp \
${TEXTA_SRC}/texta/t/variable_tree.cpp \
${TEXTA_SRC}/texta/t/variable_branch.cpp \
${TEXTA_SRC}/texta/t/variable_list.cpp \
${TEXTA_SRC}/texta/t/variable_item.cpp \
${TEXTA_SRC}/texta/t/value.cpp \
${TEXTA_SRC}/texta/t/value_list.cpp \
${TEXTA_SRC}/texta/t/value_item.cpp \
${TEXTA_SRC}/texta/t/t.cpp \
${TEXTA_SRC}/texta/io/logger.cpp \
${TEXTA_SRC}/texta/io/writer.cpp \
${TEXTA_SRC}/texta/io/reader.cpp \
${TEXTA_SRC}/texta/base/base.cpp \

texta_EXE_CPP_SOURCES += \
${TEXTA_SRC}/texta/app/console/texta/main.cpp \
${TEXTA_SRC}/texta/console/main_main.cpp \
${TEXTA_SRC}/texta/console/main_opt.cpp \

